platform :ios, '9.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'RxNetwork_Example' do
  pod 'RxNetwork/Cacheable', :path => '../'
  
  pod 'CleanJSON'
  pod 'SwiftyJSON'

  target 'RxNetwork_Tests' do
    inherit! :search_paths
    
  end
end
