platform :ios, '10.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'RxNetwork_Example' do
  pod 'RxNetwork/Cache', :path => '../'
  
  pod 'CleanJSON'

  target 'RxNetwork_Tests' do
    inherit! :search_paths
    
  end
end
